apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deploy
  namespace: streamlit-namespace
  labels:
    app: streamlit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: diwelle/streamlit:latest
        ports:
        - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: streamlit-namespace
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      nodePort: 30080
