apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-zookeeper
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath: 
    path: /kafka/kafka-zookeeper
